INPUT_BOUND_EVENTS = [
    {"event_type": "gpu_sample", "payload": {"utilization_gpu_pct": 40, "utilization_mem_pct": 35, "memory_used_bytes": 40, "memory_total_bytes": 100}},
    {"event_type": "gpu_sample", "payload": {"utilization_gpu_pct": 42, "utilization_mem_pct": 37, "memory_used_bytes": 42, "memory_total_bytes": 100}},
    {"event_type": "step_start", "step_id": 1, "payload": {"step_kind": "train"}},
    {"event_type": "dataloader_span", "step_id": 1, "duration_ns": 35, "payload": {"stage": "next"}},
    {"event_type": "phase_span", "step_id": 1, "duration_ns": 20, "payload": {"phase_name": "forward"}},
    {"event_type": "phase_span", "step_id": 1, "duration_ns": 20, "payload": {"phase_name": "backward"}},
    {"event_type": "phase_span", "step_id": 1, "duration_ns": 10, "payload": {"phase_name": "optimizer"}},
    {"event_type": "step_end", "step_id": 1, "duration_ns": 100, "payload": {"step_kind": "train", "status": "ok"}},
    {"event_type": "step_start", "step_id": 2, "payload": {"step_kind": "train"}},
    {"event_type": "dataloader_span", "step_id": 2, "duration_ns": 30, "payload": {"stage": "next"}},
    {"event_type": "phase_span", "step_id": 2, "duration_ns": 25, "payload": {"phase_name": "forward"}},
    {"event_type": "phase_span", "step_id": 2, "duration_ns": 20, "payload": {"phase_name": "backward"}},
    {"event_type": "phase_span", "step_id": 2, "duration_ns": 10, "payload": {"phase_name": "optimizer"}},
    {"event_type": "step_end", "step_id": 2, "duration_ns": 100, "payload": {"step_kind": "train", "status": "ok"}},
]

COPY_BOUND_EVENTS = [
    {"event_type": "gpu_sample", "payload": {"utilization_gpu_pct": 55, "utilization_mem_pct": 40, "memory_used_bytes": 45, "memory_total_bytes": 100}},
    {"event_type": "gpu_sample", "payload": {"utilization_gpu_pct": 58, "utilization_mem_pct": 42, "memory_used_bytes": 46, "memory_total_bytes": 100}},
    {"event_type": "step_start", "step_id": 1, "payload": {"step_kind": "train"}},
    {"event_type": "memcpy_span", "step_id": 1, "duration_ns": 20, "payload": {"copy_kind": "h2d"}},
    {"event_type": "phase_span", "step_id": 1, "duration_ns": 30, "payload": {"phase_name": "forward"}},
    {"event_type": "phase_span", "step_id": 1, "duration_ns": 25, "payload": {"phase_name": "backward"}},
    {"event_type": "phase_span", "step_id": 1, "duration_ns": 10, "payload": {"phase_name": "optimizer"}},
    {"event_type": "step_end", "step_id": 1, "duration_ns": 100, "payload": {"step_kind": "train", "status": "ok"}},
    {"event_type": "step_start", "step_id": 2, "payload": {"step_kind": "train"}},
    {"event_type": "memcpy_span", "step_id": 2, "duration_ns": 18, "payload": {"copy_kind": "h2d"}},
    {"event_type": "phase_span", "step_id": 2, "duration_ns": 30, "payload": {"phase_name": "forward"}},
    {"event_type": "phase_span", "step_id": 2, "duration_ns": 25, "payload": {"phase_name": "backward"}},
    {"event_type": "phase_span", "step_id": 2, "duration_ns": 10, "payload": {"phase_name": "optimizer"}},
    {"event_type": "step_end", "step_id": 2, "duration_ns": 100, "payload": {"step_kind": "train", "status": "ok"}},
]

SYNC_BOUND_EVENTS = [
    {"event_type": "gpu_sample", "payload": {"utilization_gpu_pct": 48, "utilization_mem_pct": 38, "memory_used_bytes": 40, "memory_total_bytes": 100}},
    {"event_type": "gpu_sample", "payload": {"utilization_gpu_pct": 50, "utilization_mem_pct": 39, "memory_used_bytes": 41, "memory_total_bytes": 100}},
    {"event_type": "step_start", "step_id": 1, "payload": {"step_kind": "train"}},
    {"event_type": "sync_wait", "step_id": 1, "duration_ns": 15, "payload": {"wait_kind": "device_sync"}},
    {"event_type": "phase_span", "step_id": 1, "duration_ns": 35, "payload": {"phase_name": "forward"}},
    {"event_type": "phase_span", "step_id": 1, "duration_ns": 25, "payload": {"phase_name": "backward"}},
    {"event_type": "phase_span", "step_id": 1, "duration_ns": 10, "payload": {"phase_name": "optimizer"}},
    {"event_type": "step_end", "step_id": 1, "duration_ns": 100, "payload": {"step_kind": "train", "status": "ok"}},
    {"event_type": "step_start", "step_id": 2, "payload": {"step_kind": "train"}},
    {"event_type": "sync_wait", "step_id": 2, "duration_ns": 12, "payload": {"wait_kind": "event_wait"}},
    {"event_type": "phase_span", "step_id": 2, "duration_ns": 35, "payload": {"phase_name": "forward"}},
    {"event_type": "phase_span", "step_id": 2, "duration_ns": 25, "payload": {"phase_name": "backward"}},
    {"event_type": "phase_span", "step_id": 2, "duration_ns": 10, "payload": {"phase_name": "optimizer"}},
    {"event_type": "step_end", "step_id": 2, "duration_ns": 100, "payload": {"step_kind": "train", "status": "ok"}},
]

LAUNCH_BOUND_EVENTS = [
    {"event_type": "gpu_sample", "payload": {"utilization_gpu_pct": 28, "utilization_mem_pct": 22, "memory_used_bytes": 30, "memory_total_bytes": 100}},
    {"event_type": "gpu_sample", "payload": {"utilization_gpu_pct": 32, "utilization_mem_pct": 24, "memory_used_bytes": 31, "memory_total_bytes": 100}},
    {"event_type": "step_start", "step_id": 1, "payload": {"step_kind": "train"}},
    {"event_type": "profiler_window", "step_id": 1, "payload": {"window_state": "exported"}},
    {"event_type": "phase_span", "step_id": 1, "duration_ns": 20, "payload": {"phase_name": "forward"}},
    {"event_type": "phase_span", "step_id": 1, "duration_ns": 15, "payload": {"phase_name": "backward"}},
    {"event_type": "phase_span", "step_id": 1, "duration_ns": 5, "payload": {"phase_name": "optimizer"}},
    {"event_type": "step_end", "step_id": 1, "duration_ns": 100, "payload": {"step_kind": "train", "status": "ok"}},
    {"event_type": "step_start", "step_id": 2, "payload": {"step_kind": "train"}},
    {"event_type": "profiler_window", "step_id": 2, "payload": {"window_state": "exported"}},
    {"event_type": "phase_span", "step_id": 2, "duration_ns": 18, "payload": {"phase_name": "forward"}},
    {"event_type": "phase_span", "step_id": 2, "duration_ns": 17, "payload": {"phase_name": "backward"}},
    {"event_type": "phase_span", "step_id": 2, "duration_ns": 5, "payload": {"phase_name": "optimizer"}},
    {"event_type": "step_end", "step_id": 2, "duration_ns": 100, "payload": {"step_kind": "train", "status": "ok"}},
]

MEMORY_PRESSURE_EVENTS = [
    {"event_type": "gpu_sample", "payload": {"utilization_gpu_pct": 72, "utilization_mem_pct": 91, "memory_used_bytes": 93, "memory_total_bytes": 100}},
    {"event_type": "gpu_sample", "payload": {"utilization_gpu_pct": 70, "utilization_mem_pct": 89, "memory_used_bytes": 95, "memory_total_bytes": 100}},
    {"event_type": "step_start", "step_id": 1, "payload": {"step_kind": "train"}},
    {"event_type": "phase_span", "step_id": 1, "duration_ns": 35, "payload": {"phase_name": "forward"}},
    {"event_type": "phase_span", "step_id": 1, "duration_ns": 35, "payload": {"phase_name": "backward"}},
    {"event_type": "phase_span", "step_id": 1, "duration_ns": 10, "payload": {"phase_name": "optimizer"}},
    {"event_type": "step_end", "step_id": 1, "duration_ns": 100, "payload": {"step_kind": "train", "status": "ok"}},
    {"event_type": "step_start", "step_id": 2, "payload": {"step_kind": "train"}},
    {"event_type": "phase_span", "step_id": 2, "duration_ns": 35, "payload": {"phase_name": "forward"}},
    {"event_type": "phase_span", "step_id": 2, "duration_ns": 35, "payload": {"phase_name": "backward"}},
    {"event_type": "phase_span", "step_id": 2, "duration_ns": 10, "payload": {"phase_name": "optimizer"}},
    {"event_type": "step_end", "step_id": 2, "duration_ns": 100, "payload": {"step_kind": "train", "status": "ok"}},
]

SHAPE_INSTABILITY_EVENTS = [
    {"event_type": "gpu_sample", "payload": {"utilization_gpu_pct": 68, "utilization_mem_pct": 50, "memory_used_bytes": 52, "memory_total_bytes": 100}},
    {"event_type": "gpu_sample", "payload": {"utilization_gpu_pct": 70, "utilization_mem_pct": 52, "memory_used_bytes": 54, "memory_total_bytes": 100}},
    {"event_type": "step_start", "step_id": 1, "payload": {"step_kind": "train"}},
    {"event_type": "shape_snapshot", "step_id": 1, "payload": {"batch_size": 16, "sequence_length": 128, "shapes": {"input_ids": [16, 128], "attention_mask": [16, 128]}}},
    {"event_type": "phase_span", "step_id": 1, "duration_ns": 30, "payload": {"phase_name": "forward"}},
    {"event_type": "phase_span", "step_id": 1, "duration_ns": 30, "payload": {"phase_name": "backward"}},
    {"event_type": "phase_span", "step_id": 1, "duration_ns": 10, "payload": {"phase_name": "optimizer"}},
    {"event_type": "step_end", "step_id": 1, "duration_ns": 100, "payload": {"step_kind": "train", "status": "ok"}},
    {"event_type": "step_start", "step_id": 2, "payload": {"step_kind": "train"}},
    {"event_type": "shape_snapshot", "step_id": 2, "payload": {"batch_size": 16, "sequence_length": 256, "shapes": {"input_ids": [16, 256], "attention_mask": [16, 256]}}},
    {"event_type": "phase_span", "step_id": 2, "duration_ns": 30, "payload": {"phase_name": "forward"}},
    {"event_type": "phase_span", "step_id": 2, "duration_ns": 30, "payload": {"phase_name": "backward"}},
    {"event_type": "phase_span", "step_id": 2, "duration_ns": 10, "payload": {"phase_name": "optimizer"}},
    {"event_type": "step_end", "step_id": 2, "duration_ns": 100, "payload": {"step_kind": "train", "status": "ok"}},
    {"event_type": "step_start", "step_id": 3, "payload": {"step_kind": "train"}},
    {"event_type": "shape_snapshot", "step_id": 3, "payload": {"batch_size": 16, "sequence_length": 128, "shapes": {"input_ids": [16, 128], "attention_mask": [16, 128]}}},
    {"event_type": "phase_span", "step_id": 3, "duration_ns": 30, "payload": {"phase_name": "forward"}},
    {"event_type": "phase_span", "step_id": 3, "duration_ns": 30, "payload": {"phase_name": "backward"}},
    {"event_type": "phase_span", "step_id": 3, "duration_ns": 10, "payload": {"phase_name": "optimizer"}},
    {"event_type": "step_end", "step_id": 3, "duration_ns": 100, "payload": {"step_kind": "train", "status": "ok"}},
]

MIXED_SIGNAL_EVENTS = [
    {"event_type": "gpu_sample", "payload": {"utilization_gpu_pct": 33, "utilization_mem_pct": 37, "memory_used_bytes": 45, "memory_total_bytes": 100}},
    {"event_type": "gpu_sample", "payload": {"utilization_gpu_pct": 35, "utilization_mem_pct": 38, "memory_used_bytes": 46, "memory_total_bytes": 100}},
    {"event_type": "step_start", "step_id": 1, "payload": {"step_kind": "train"}},
    {"event_type": "dataloader_span", "step_id": 1, "duration_ns": 28, "payload": {"stage": "next"}},
    {"event_type": "memcpy_span", "step_id": 1, "duration_ns": 19, "payload": {"copy_kind": "h2d"}},
    {"event_type": "phase_span", "step_id": 1, "duration_ns": 20, "payload": {"phase_name": "forward"}},
    {"event_type": "phase_span", "step_id": 1, "duration_ns": 18, "payload": {"phase_name": "backward"}},
    {"event_type": "phase_span", "step_id": 1, "duration_ns": 5, "payload": {"phase_name": "optimizer"}},
    {"event_type": "step_end", "step_id": 1, "duration_ns": 100, "payload": {"step_kind": "train", "status": "ok"}},
    {"event_type": "step_start", "step_id": 2, "payload": {"step_kind": "train"}},
    {"event_type": "dataloader_span", "step_id": 2, "duration_ns": 24, "payload": {"stage": "next"}},
    {"event_type": "memcpy_span", "step_id": 2, "duration_ns": 17, "payload": {"copy_kind": "h2d"}},
    {"event_type": "phase_span", "step_id": 2, "duration_ns": 21, "payload": {"phase_name": "forward"}},
    {"event_type": "phase_span", "step_id": 2, "duration_ns": 18, "payload": {"phase_name": "backward"}},
    {"event_type": "phase_span", "step_id": 2, "duration_ns": 5, "payload": {"phase_name": "optimizer"}},
    {"event_type": "step_end", "step_id": 2, "duration_ns": 100, "payload": {"step_kind": "train", "status": "ok"}},
]

SPARSE_TELEMETRY_EVENTS = [
    {"event_type": "step_start", "step_id": 1, "payload": {"step_kind": "train"}},
    {"event_type": "step_end", "step_id": 1, "duration_ns": 100, "payload": {"step_kind": "train", "status": "ok"}},
    {"event_type": "step_start", "step_id": 2, "payload": {"step_kind": "train"}},
    {"event_type": "step_end", "step_id": 2, "duration_ns": 120, "payload": {"step_kind": "train", "status": "ok"}},
]
