"""Tests for the training-telemetry explain path (frx_telemetry_explain_v0)."""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "python"))
sys.path.insert(0, str(ROOT / "tests" / "python"))

import fournex as fn
from fournex.analysis import summarize_step_scope
from fournex.explain import (
    build_telemetry_explain_result,
    render_training_summary_txt,
    render_training_llm_prompt_txt,
    render_evidence_json,
    _select_scope_data,
)
from analysis_bottleneck_golden_cases import (
    LAUNCH_BOUND_TINY_KERNEL_EVENTS,
    INPUT_BOUND_EVENTS,
)


# ── Fixtures ──────────────────────────────────────────────────────────────────

def _launch_scope():
    return summarize_step_scope(LAUNCH_BOUND_TINY_KERNEL_EVENTS)

def _input_scope():
    return summarize_step_scope(INPUT_BOUND_EVENTS)


# ── build_telemetry_explain_result ────────────────────────────────────────────

def test_result_schema():
    result = build_telemetry_explain_result(scope_data=_launch_scope())
    assert result["schema"] == "frx_telemetry_explain_v0"


def test_result_has_required_keys():
    result = build_telemetry_explain_result(scope_data=_launch_scope())
    for key in ("schema", "scope_name", "step_count", "primary_bottleneck",
                "secondary_bottlenecks", "confidence", "why", "key_metrics",
                "phase_fractions", "top_recommendations", "framework_abstraction_tax",
                "missing_data", "bottleneck_evidence"):
        assert key in result, f"missing key: {key}"


def test_launch_bound_primary_bottleneck():
    result = build_telemetry_explain_result(scope_data=_launch_scope())
    assert result["primary_bottleneck"] is not None


def test_input_bound_primary_bottleneck():
    result = build_telemetry_explain_result(scope_data=_input_scope())
    assert result["primary_bottleneck"] is not None


def test_key_metrics_contains_gpu_utilization():
    result = build_telemetry_explain_result(scope_data=_launch_scope())
    assert "average_gpu_utilization_pct" in result["key_metrics"]


def test_framework_abstraction_tax_present_for_launch_bound():
    result = build_telemetry_explain_result(scope_data=_launch_scope())
    fat = result.get("framework_abstraction_tax")
    assert fat is not None
    assert fat["score"] > 0


def test_top_recommendations_list():
    result = build_telemetry_explain_result(scope_data=_launch_scope())
    assert isinstance(result["top_recommendations"], list)
    for r in result["top_recommendations"]:
        assert "title" in r
        assert "priority" in r


def test_secondary_bottlenecks_exclude_primary():
    result = build_telemetry_explain_result(scope_data=_launch_scope())
    primary = result["primary_bottleneck"]
    assert primary not in result["secondary_bottlenecks"]


def test_phase_fractions_input_bound():
    result = build_telemetry_explain_result(scope_data=_input_scope())
    # input_bound evidence should populate input_bound fraction
    if result["primary_bottleneck"] == "input_bound":
        assert "input_bound" in result["phase_fractions"]
        assert result["phase_fractions"]["input_bound"] > 0


# ── render_training_summary_txt ───────────────────────────────────────────────

def test_summary_has_primary_bottleneck_section():
    result = build_telemetry_explain_result(scope_data=_launch_scope())
    txt = render_training_summary_txt(result)
    assert "PRIMARY BOTTLENECK" in txt


def test_summary_has_key_metrics_section():
    result = build_telemetry_explain_result(scope_data=_launch_scope())
    txt = render_training_summary_txt(result)
    assert "KEY METRICS" in txt
    assert "GPU Utilization" in txt


def test_summary_has_what_to_fix_section():
    result = build_telemetry_explain_result(scope_data=_launch_scope())
    txt = render_training_summary_txt(result)
    assert "WHAT TO FIX FIRST" in txt


def test_summary_shows_fat_when_high():
    result = build_telemetry_explain_result(scope_data=_launch_scope())
    txt = render_training_summary_txt(result)
    fat = result.get("framework_abstraction_tax")
    if fat and fat.get("score", 0) >= 20:
        assert "FRAMEWORK ABSTRACTION TAX" in txt


def test_summary_run_id_appears():
    result = build_telemetry_explain_result(scope_data=_launch_scope())
    txt = render_training_summary_txt(result, run_id="test-run-abc")
    assert "test-run-abc" in txt


def test_summary_generated_by_footer():
    result = build_telemetry_explain_result(scope_data=_launch_scope())
    txt = render_training_summary_txt(result)
    assert "Generated by Fournex" in txt


# ── render_training_llm_prompt_txt ────────────────────────────────────────────

def test_prompt_has_training_header():
    result = build_telemetry_explain_result(scope_data=_launch_scope())
    txt = render_training_llm_prompt_txt(result)
    assert "PyTorch Training Loop Optimization" in txt


def test_prompt_has_guardrails():
    result = build_telemetry_explain_result(scope_data=_launch_scope())
    txt = render_training_llm_prompt_txt(result)
    assert "correctness" in txt.lower()


def test_prompt_has_primary_bottleneck():
    result = build_telemetry_explain_result(scope_data=_launch_scope())
    txt = render_training_llm_prompt_txt(result)
    assert "PRIMARY BOTTLENECK" in txt


def test_prompt_has_training_evidence_section():
    result = build_telemetry_explain_result(scope_data=_launch_scope())
    txt = render_training_llm_prompt_txt(result)
    assert "TRAINING EVIDENCE" in txt
    assert "GPU utilization" in txt


def test_prompt_has_specific_question():
    result = build_telemetry_explain_result(scope_data=_launch_scope())
    txt = render_training_llm_prompt_txt(result)
    assert "SPECIFIC QUESTION" in txt


def test_prompt_has_rerun_note():
    result = build_telemetry_explain_result(scope_data=_launch_scope())
    txt = render_training_llm_prompt_txt(result)
    assert "frx collect" in txt or "re-collect" in txt.lower()


def test_prompt_launch_bound_question_mentions_compile_or_graphs():
    result = build_telemetry_explain_result(scope_data=_launch_scope())
    if result["primary_bottleneck"] == "launch_bound":
        txt = render_training_llm_prompt_txt(result)
        question_section = txt.split("SPECIFIC QUESTION")[1]
        assert "compile" in question_section.lower() or "graph" in question_section.lower()


def test_prompt_shows_fat_section_when_high():
    result = build_telemetry_explain_result(scope_data=_launch_scope())
    fat = result.get("framework_abstraction_tax")
    if fat and fat.get("score", 0) >= 20:
        txt = render_training_llm_prompt_txt(result)
        assert "FRAMEWORK ABSTRACTION TAX" in txt


def test_prompt_secondary_excluded_from_secondary_section():
    result = build_telemetry_explain_result(scope_data=_launch_scope())
    txt = render_training_llm_prompt_txt(result)
    # If SECONDARY ISSUES present, primary should not appear there
    if "SECONDARY ISSUES" in txt:
        primary = result["primary_bottleneck"] or ""
        secondary_block = txt.split("SECONDARY ISSUES")[1].split("FRAMEWORK")[0]
        assert primary.replace("_", " ") not in secondary_block


# ── render_evidence_json ──────────────────────────────────────────────────────

def test_evidence_json_is_valid():
    result = build_telemetry_explain_result(scope_data=_launch_scope())
    raw = render_evidence_json(result)
    parsed = json.loads(raw)
    assert parsed["schema"] == "frx_telemetry_explain_v0"


# ── _select_scope_data ────────────────────────────────────────────────────────

def test_select_scope_auto_prefers_steady_state():
    summary = {"steady_state": {"tag": "ss"}, "run": {"tag": "run"}}
    assert _select_scope_data(summary, "auto")["tag"] == "ss"


def test_select_scope_auto_falls_back_to_run():
    summary = {"run": {"tag": "run"}}
    assert _select_scope_data(summary, "auto")["tag"] == "run"


def test_select_scope_explicit_run():
    summary = {"steady_state": {"tag": "ss"}, "run": {"tag": "run"}}
    assert _select_scope_data(summary, "run")["tag"] == "run"


# ── module exports ────────────────────────────────────────────────────────────

def test_new_functions_exported_from_fournex():
    assert hasattr(fn, "build_telemetry_explain_result")
    assert hasattr(fn, "render_training_summary_txt")
    assert hasattr(fn, "render_training_llm_prompt_txt")
